public enum ItemType
{
    Null = 0,
    ChestArmor = 1,
    Helm = 2,
    Shield = 3,
    Buff = 4,
    Shoes = 5,
    LightSource = 6,
    Currency = 7,
    Consumption = 8, 
    Material = 9,
    Arrow = 10,
    Bullet = 11,
    Bow = 12,
    Sword = 13,
    Axe = 14,
    Hammer = 15,
    CombatDummy = 16,
    Boomerang = 17,
    MagicStaff = 18,
    Chest = 19,
    Workbench = 20,
}
